/***
 * File name: meta.js
 *
 * Program Description:
 * A set of meta variables used in different parts of the application.
 *
 * Module Exports:
 * - usernameRegex: regex validation for creating a user name
 * - passwordRegex: regex validation for creating a password
 * - padDate: boolean for default date padding
 * - padTimes: boolean for default time padding
 * - guestUserTemplate: default template for seeding a guest user
 * - adminUserTemplate: default template for seeding an admin user
 * - usernamePath: Setting per user role for user name basis
 * - maxFileUploadSize: Max upload size per file within the application
 * - defaultPassword: default password used by seeded users
 */

/* eslint-disable no-control-regex */
/* eslint-disable no-useless-escape */
/* eslint-disable require-unicode-regexp */
/* eslint-disable prefer-named-capture-group */


/* eslint-disable no-control-regex */
/* eslint-disable no-useless-escape */
/* eslint-disable require-unicode-regexp */
/* eslint-disable prefer-named-capture-group */

const meta = {
    // eslint-disable-next-line security/detect-unsafe-regex
    usernameRegex: /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/,
    passwordRegex: new RegExp('.{8,}'),
    changePasswordRegex: /^(?=.*[A-Z])(?=.*[!@#$%^&*_-])(?=.*[0-9])[a-zA-Z0-9!@#$%^&*_-]{8,100}$/u,
    padDates: true,
    padTimes: false,
    dateFormat: '%Y-%m-%d',
    timezone: 'Asia/Manila',
    defaultPassword: 'RaGpKJhZ@764',
    guestUserTemplate: {
        employeeType: 'Probationary Employee',
        role: 'Guest',
        firstName: 'Guest',
        middleName: '',
        lastName: 'User',
        position: 'New Hire',
        employeeId: "123",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'guest@sample.com',
        mobileNumber: '(+63)1234567890',
        userType: 'External',
        userRole: [ 'guest' ],
        createdBy: null,
        updatedBy: null,
        password: 'RaGpKJhZ@764'
    },
    accountingOfficerTemplate: {
        employeeType: 'Probationary Employee',
        role: 'Accounting Unit Head/Officer',
        firstName: 'Accounting',
        middleName: '',
        lastName: 'Officer',
        position: 'New Hire',
        employeeId: "124",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'accountingOfficer@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'accountingOfficer' ],
        createdBy: null,
        updatedBy: null
    },
    budgetOfficerTemplate: {
        employeeType: 'Probationary Employee',
        role: 'Budget Officer',
        firstName: 'Budget',
        middleName: '',
        lastName: 'Officer',
        position: 'New Hire',
        employeeId: "125",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'budgetOfficer@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'budgetOfficer' ],
        createdBy: null,
        updatedBy: null
    },
    cashierTemplate: {
        employeeType: 'Probationary Employee',
        role: 'Cashier',
        firstName: 'Cashier',
        middleName: '',
        lastName: 'User',
        position: 'New Hire',
        employeeId: "9698301",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'cashier@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'cashier' ],
        createdBy: null,
        updatedBy: null
    },
    directorTemplate: {
        employeeType: 'Regular Employee',
        role: 'Director',
        firstName: 'Director',
        middleName: '',
        lastName: 'Head',
        position: 'Head',
        employeeId: "126",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'director@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'director' ],
        createdBy: null,
        updatedBy: null
    },
    hrOfficerTemplate: {
        employeeType: 'Regular Employee',
        role: 'HR Officer',
        firstName: 'HR',
        middleName: '',
        lastName: 'Officer',
        position: 'Head',
        employeeId: "127",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'hrOfficer@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'hrOfficer' ],
        createdBy: null,
        updatedBy: null
    },
    inventoryOfficerTemplate: {
        employeeType: 'Regular Employee',
        role: 'Supply and Inventory Officer',
        firstName: 'Inventory',
        middleName: '',
        lastName: 'Officer',
        position: 'Head',
        employeeId: "128",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'inventoryOfficer@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'inventoryOfficer' ],
        createdBy: null,
        updatedBy: null
    },
    procurementOfficerTemplate: {
        employeeType: 'Regular Employee',
        role: 'Procurement Officer',
        firstName: 'Procurement',
        middleName: '',
        lastName: 'Officer',
        position: 'Head',
        employeeId: "129",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'procurementOfficer@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'procurementOfficer' ],
        createdBy: null,
        updatedBy: null
    },
    projectLeaderTemplate: {
        employeeType: 'Regular Employee',
        role: 'Project Leader',
        firstName: 'Project',
        lastName: 'Leader',
        position: 'Top',
        employeeId: "593787",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'projectLeader@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'projectLeader' ],
        createdBy: null,
        updatedBy: null
    },
    adminUserTemplate: {
        employeeType: 'Regular Employee',
        role: 'IT Admin',
        firstName: 'Admin',
        lastName: 'User',
        position: 'Top',
        employeeId: "1234",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'user@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'admin' ],
        createdBy: null,
        updatedBy: null
    },
    superAdminUserTemplate: {
        employeeType: 'Regular Employee',
        role: 'Super Admin',
        firstName: 'Super',
        lastName: 'Admin',
        position: 'Top',
        employeeId: "9999",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'super@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'superadmin' ],
        createdBy: null,
        updatedBy: null
    },
    fadChiefUserTemplate: {
        employeeType: 'Regular Employee',
        role: 'FAD Chief',
        firstName: 'FAD',
        lastName: 'Chief',
        position: 'Top',
        employeeId: "91235",
        department: 'Test Department',
        immediateSupervisor: 'Test',
        dateOfEmployment: '04-01-2021',
        dateOfBirth: '04-01-1990',
        email: 'fadChief@mail.com',
        mobileNumber: '(+63)1234567890',
        userType: 'Internal',
        userRole: [ 'fadChief' ],
        createdBy: null,
        updatedBy: null
    },
    usernamePath: {
        default: 'email',
        superadmin: 'email',
        admin: 'email',
        guest: 'email',
        accountingOfficer: 'email',
        budgetOfficer: 'email',
        director: 'email',
        hrOfficer: 'email',
        inventoryOfficer: 'email',
        procurementOfficer: 'email',
        adminUser: 'email',
        fadChief: 'email',
        projectLeader: 'email',
        cashier: 'email'
    },
    initialDeactivationReasons: [ 'The user has resigned.' ],
    salutations: [
        '',
        "Mr.",
        "Mrs.",
        "Miss",
        "Dr.",
        "Ms.",
        "Prof.",
        "Rev.",
        "Lady",
        "Sir",
        "Capt.",
        "Major",
        "Lt.-Col.",
        "Col.",
        "Lady",
        "Lt.-Cmdr.",
        "The Hon.",
        "Cmdr.",
        "Flt. Lt.",
        "Brgdr.",
        "Judge",
        "Lord",
        "The Hon. Mrs",
        "Wng. Cmdr.",
        "Group Capt.",
        "Rt. Hon. Lord",
        "Revd. Father",
        "Revd Canon",
        "Maj.-Gen.",
        "Air Cdre.",
        "Viscount",
        "Dame",
        "Rear Admrl.",
        "Dir.",
        "Hon."
    ],
    FOR_BUDGET: 'For Budget',
    FOR_ACCOUNTING: 'For Accounting',
    FOR_CASHIER: 'For Cashier',
    COMPLETED: 'Completed',
    maxFileUploadSize: 52428800,
    HARD_DELETE: {
        ACTUAL_EXPENSES: true,
        CAMPUS: true,
        DEPARTMENT: true,
        EQUIPMENT: true,
        FINANCE: false,
        ITEM_TYPE: true,
        LINE_ITEM_BUDGET: true,
        PROJECT: true,
        PROJECT_TASK: true,
        PROJECT_TYPE: true,
        SUPPLIER: true
    }
}

module.exports = meta